### ISSUE TITLE
Use download_artifact for helm diff plugin

### ISSUE THREAD

**Issue by cuttingedge1109** [vexxhost/ansible-collection-kubernetes#28]
I love to use this collection for the k8s installation in the air-gap environment.
But i found that there is one task using online github to install helm diff plugin.
I think this can be installed by using `download_artifact` also.
Cheers.

**Comment by mnaser** [comment]
ah yes, good catch.  we will hope to fix this soon.

**Comment by cuttingedge1109** [comment]
thanks
