### ISSUE TITLE
fr: Support nvidia device plugin

### ISSUE THREAD

**Issue by cuttingedge1109** [vexxhost/ansible-collection-kubernetes#29]
https://github.com/NVIDIA/k8s-device-plugin#configure-containerd
I think this collection can simply support GPU on K8s cluster by configuring containerd.

**Comment by mnaser** [comment]
@cuttingedge1109: the documentation you've provided seems to list that it involves changing the default runtime name.  do you know if it's possible to configure the nvidia gpu configs but not change the default? (so we can make that opt-in?)

**Comment by ricolin** [comment]
There's also a GPU operator that might suit our needs here https://github.com/NVIDIA/gpu-operator

**Comment by ricolin** [comment]
Saw someone else using that from https://etherpad.opendev.org/p/openinfra-2023-kubernetes-on-openstack#L51
And it seems to work fine for them

**Comment by cuttingedge1109** [comment]
@mnaser I don't think that can be optional.
If we can override/append custom configurations in the containerd toml file, we can define different runtimes per host or host group easily.
How about this?

**Comment by cuttingedge1109** [comment]
@ricolin yeah, we tried that but it doesn't support centos8 stream so we don't use that operator.

**Comment by cuttingedge1109** [comment]
we will look into this again in the future and now using warewulf4 for clustering instead of k8s.
