### ISSUE TITLE
Fail to run TASK [vexxhost.kubernetes.cluster_api : Run upgrade if required]

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/ansible-collection-kubernetes#35]
```sh
TASK [vexxhost.kubernetes.cluster_api : Run upgrade if required] ***************
fatal: [ctl1]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/clusterctl", "upgrade", "apply", "--config", "/etc/clusterctl.yaml", "--core", "capi-system/cluster-api:v1.4.4", "--bootstrap", "capi-kubeadm-bootstrap-system/kubeadm:v1.4.4", "--control-plane", "capi-kubeadm-control-plane-system/kubeadm:v1.4.4", "--infrastructure", "capo-system/openstack:v0.7.1"], "delta": "0:01:03.388960", "end": "2023-07-05 12:42:33.305584", "msg": "non-zero return code", "rc": 1, "start": "2023-07-05 12:41:29.916624", "stderr": "Performing upgrade...\nError: failed to read \"metadata.yaml\" from the repository for provider \"infrastructure-openstack\": failed to get GitHub release v0.8.0-alpha.0: failed to read release \"v0.8.0-alpha.0\": GET https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-openstack/releases/tags/v0.8.0-alpha.0: 404 Not Found []", "stderr_lines": ["Performing upgrade...", "Error: failed to read \"metadata.yaml\" from the repository for provider \"infrastructure-openstack\": failed to get GitHub release v0.8.0-alpha.0: failed to read release \"v0.8.0-alpha.0\": GET https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-openstack/releases/tags/v0.8.0-alpha.0: 404 Not Found []"], "stdout": "", "stdout_lines": []}
```

**Comment by mnaser** [comment]
This is due to https://github.com/kubernetes/k8s.io/pull/5510 not being merged.

**Comment by mdbooth** [comment]
> This is due to [kubernetes/k8s.io#5510](https://github.com/kubernetes/k8s.io/pull/5510) not being merged.

I don't think so. It's looking for https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-openstack/releases/tags/v0.8.0-alpha.0 which exists but isn't published yet. The primary reason it isn't published is because https://github.com/kubernetes/k8s.io/pull/5510 isn't merged, but I'm pretty sure that's incidental.

I think this may be a bug in either clusterctl (assuming a release exists for a tag) or GH (returning a release which isn't published).

**Comment by mnaser** [comment]
> This may be fixed in [kubernetes-sigs/cluster-api#7889](https://github.com/kubernetes-sigs/cluster-api/issues/7889).

Ah, indeed, you're right.  I tested it with 1.4.4 and no good but the 1.5.0-beta.0 (which includes the fix) seems to have it.

I filed https://github.com/kubernetes-sigs/cluster-api/issues/8966 upstream in the meantime.

**Comment by mnaser** [comment]
For users of this collection, the workaround for now is to login to one of the systems and run this:

```
GOPROXY=off clusterctl upgrade apply \
  --config /etc/clusterctl.yaml \
  --core capi-system/cluster-api:v1.4.4 \
  --bootstrap capi-kubeadm-bootstrap-system/kubeadm:v1.4.4 \
  --control-plane capi-kubeadm-control-plane-system/kubeadm:v1.4.4 \
  --infrastructure capo-system/openstack:v0.7.1
```

With that, it should be able to unblock this, and you should be able to run the rest of the roles with no issues.

**Comment by mnaser** [comment]
https://github.com/kubernetes-sigs/cluster-api/issues/7889 seems to continue the discussion here.
